spring:
  application:
    name: Euxoulides

  datasource:
    url: jdbc:postgresql://ep-quiet-credit-ags5csnl-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_rqdOGz1EF4YP
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

tmdb:
  api:
    key: ${TMDB_API_KEY}
  base:
    url: https://api.themoviedb.org/3

google:
  client-id: 1005494521790-5tisd69v12pj2cqsjmfi7eru6lhhv7lh.apps.googleusercontent.com
  key: d166af459b20ece5176f1e92a23e3aa1
